fcm:
  credential-path: firebase/one-two-three.json
  scope: https://www.googleapis.com/auth/firebase.messaging

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/onetwothree?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ddd
    password: onetwothree!
    driver-class-name: com.mysql.cj.jdbc.Driver